language: node_js
node_js: '8'
cache:
  directories:
  - node_modules
after_success:
  - vuepress build docs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  on:
    branch: master